In [ ]:
setwd("splicing")

library(plyr)
library(dplyr)
library(qvalue)
library(msigdbr)
library(data.table)

source("code/enrichment_analysis.R")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

In [3]:
msigdb <- msigdbr(species="Mus musculus", category="C5")
sets <- tapply(msigdb$gene_symbol, INDEX=msigdb$gs_name, FUN=list)
sets <- sets[grep("^GO", names(sets))]

# Ctrl vs. CalTRAP naive

In [4]:
experiment_path <- "data/rmats/batch2/ctrl_vs_naive"

In [5]:
# Combine all splicing events to get background

all_files <- list.files(path=experiment_path, pattern="fromGTF\\.[^.]+\\.txt")

all_events_list <- lapply(all_files, function(x) {
    fread(file.path(experiment_path, x), data.table=FALSE)
})
all_events_df <- do.call(rbind.fill, all_events_list)

In [6]:
# Combine singificant splicing events

signif_files <- list.files(path=experiment_path, pattern="filtered")

signif_events_list <- lapply(signif_files, function(x) {
    df <- fread(file.path(experiment_path, x), data.table=FALSE)
    df$Event_type <- unlist(strsplit(x, split=".", fixed=TRUE))[1]
    df
})
signif_events_df <- do.call(rbind.fill, signif_events_list)

In [7]:
all_genes <- unique(all_events_df$geneSymbol)
print(length(all_genes))

[1] 13845

## All significant events

In [8]:
signif_genes <- unique(signif_events_df$geneSymbol)
print(length(signif_genes))

[1] 1255

In [9]:
enrich_df <- get_enrich(signif_genes, all_genes, sets)
head(enrich_df, 20)

                                                  Pval         P.adj
GOCC_NEURON_PROJECTION                            1.025037e-23 1.065936e-19
GOCC_AXON                                         1.677894e-20 8.724210e-17
GOCC_SYNAPSE                                      8.601018e-20 2.981400e-16
GOBP_NEURON_DIFFERENTIATION                       8.629347e-15 2.243414e-11
GOBP_CELL_JUNCTION_ORGANIZATION                   3.971728e-14 8.260400e-11
GOBP_VESICLE_MEDIATED_TRANSPORT                   9.123664e-14 1.581283e-10
GOBP_NEURON_DEVELOPMENT                           1.889219e-13 2.806569e-10
GOCC_NEURON_TO_NEURON_SYNAPSE                     3.377636e-13 4.390504e-10
GOMF_NUCLEOSIDE_TRIPHOSPHATASE_REGULATOR_ACTIVITY 4.294594e-13 4.962165e-10
GOBP_CELL_PART_MORPHOGENESIS                      1.255849e-12 1.305957e-09
GOBP_NEUROGENESIS                                 1.924422e-12 1.819278e-09
GOCC_POSTSYNAPSE                                  2.445261e-12 2.119023e-09
GOBP_CELLULAR_COMPONENT_MORPHOGENESIS             3.549574e-12 2.839386e-09
GOCC_SOMATODENDRITIC_COMPARTMENT                  7.788964e-12 5.785531e-09
GOBP_CYTOSKELETON_ORGANIZATION                    2.213179e-11 1.534323e-08
GOBP_CELL_PROJECTION_ORGANIZATION                 8.324524e-11 5.410421e-08
GOCC_GOLGI_APPARATUS                              1.305233e-10 7.984184e-08
GOBP_CELL_MORPHOGENESIS                           1.539116e-10 8.891814e-08
GOBP_REGULATION_OF_CELL_PROJECTION_ORGANIZATION   1.922513e-10 1.052222e-07
GOMF_GTPASE_ACTIVATOR_ACTIVITY                    2.449619e-10 1.273679e-07

## Retained introns

### Negative values corresponds to more retained introns in CalTRAP samples

In [10]:
RI_cal_df <- signif_events_df[(signif_events_df$Event_type == "RI") & (signif_events_df$IncLevelDifference < 0),]
RI_cal_genes <- unique(RI_cal_df$geneSymbol)
print(length(RI_cal_genes))

[1] 69

In [11]:
enrich_RI_cal_df <- get_enrich(RI_cal_genes, all_genes, sets)
head(enrich_RI_cal_df, 20)

                                                                             Pval
GOBP_MRNA_PROCESSING                                                         5.663612e-05
GOBP_RNA_PROCESSING                                                          9.564472e-05
GOBP_PROTEIN_MATURATION                                                      5.405277e-04
GOMF_RNA_BINDING                                                             5.823607e-04
GOBP_REGULATION_OF_MRNA_METABOLIC_PROCESS                                    8.800312e-04
GOBP_MRNA_METABOLIC_PROCESS                                                  9.097294e-04
GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS 9.350787e-04
GOBP_REGULATION_OF_MRNA_PROCESSING                                           2.121282e-03
GOBP_MITOCHONDRIAL_CYTOCHROME_C_OXIDASE_ASSEMBLY                             2.143061e-03
GOMF_DNA_POLYMERASE_BINDING                                                  2.143061e-03
GOBP_RESPIRATORY_CHAIN_COMPLEX_IV_ASSEMBLY                                   2.464817e-03
GOMF_SMAD_BINDING                                                            2.582312e-03
GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS                            2.726793e-03
GOBP_TRANSFORMING_GROWTH_FACTOR_BETA_RECEPTOR_SIGNALING_PATHWAY              2.743965e-03
GOBP_REGULATION_OF_RNA_SPLICING                                              3.191043e-03
GOBP_MITOCHONDRIAL_RESPIRATORY_CHAIN_COMPLEX_ASSEMBLY                        3.309083e-03
GOCC_FILAMENTOUS_ACTIN                                                       3.962835e-03
GOCC_POLYSOMAL_RIBOSOME                                                      3.962835e-03
GOMF_R_SMAD_BINDING                                                          3.962835e-03
GOBP_RNA_SPLICING                                                            4.409848e-03
                                                                             P.adj
GOBP_MRNA_PROCESSING                                                         0.4973047
GOBP_RNA_PROCESSING                                                          0.4973047
GOBP_PROTEIN_MATURATION                                                      1.0000000
GOMF_RNA_BINDING                                                             1.0000000
GOBP_REGULATION_OF_MRNA_METABOLIC_PROCESS                                    1.0000000
GOBP_MRNA_METABOLIC_PROCESS                                                  1.0000000
GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS 1.0000000
GOBP_REGULATION_OF_MRNA_PROCESSING                                           1.0000000
GOBP_MITOCHONDRIAL_CYTOCHROME_C_OXIDASE_ASSEMBLY                             1.0000000
GOMF_DNA_POLYMERASE_BINDING                                                  1.0000000
GOBP_RESPIRATORY_CHAIN_COMPLEX_IV_ASSEMBLY                                   1.0000000
GOMF_SMAD_BINDING                                                            1.0000000
GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS                            1.0000000
GOBP_TRANSFORMING_GROWTH_FACTOR_BETA_RECEPTOR_SIGNALING_PATHWAY              1.0000000
GOBP_REGULATION_OF_RNA_SPLICING                                              1.0000000
GOBP_MITOCHONDRIAL_RESPIRATORY_CHAIN_COMPLEX_ASSEMBLY                        1.0000000
GOCC_FILAMENTOUS_ACTIN                                                       1.0000000
GOCC_POLYSOMAL_RIBOSOME                                                      1.0000000
GOMF_R_SMAD_BINDING                                                          1.0000000
GOBP_RNA_SPLICING                                                            1.0000000

### Positive values corresponds to more retained introns in control samples

In [12]:
RI_ctrl_df <- signif_events_df[(signif_events_df$Event_type == "RI") & (signif_events_df$IncLevelDifference > 0),]
RI_ctrl_genes <- unique(RI_ctrl_df$geneSymbol)
print(length(RI_ctrl_genes))

[1] 25

In [13]:
enrich_RI_ctrl_df <- get_enrich(RI_ctrl_genes, all_genes, sets)
head(enrich_RI_ctrl_df, 20)

                                                                                                                                                                 Pval
GOBP_MOTOR_NEURON_MIGRATION                                                                                                                                      0.005407732
GOBP_NEURAL_CREST_CELL_MIGRATION_INVOLVED_IN_AUTONOMIC_NERVOUS_SYSTEM_DEVELOPMENT                                                                                0.005407732
GOBP_TRNA_THIO_MODIFICATION                                                                                                                                      0.005407732
GOCC_FIBRINOGEN_COMPLEX                                                                                                                                          0.005407732
GOBP_ORGANELLE_LOCALIZATION                                                                                                                                      0.005413684
GOBP_MAINTENANCE_OF_PRESYNAPTIC_ACTIVE_ZONE_STRUCTURE                                                                                                            0.007204063
GOMF_STRUCTURAL_CONSTITUENT_OF_PRESYNAPTIC_ACTIVE_ZONE                                                                                                           0.007204063
GOBP_RIBOSOME_ASSOCIATED_UBIQUITIN_DEPENDENT_PROTEIN_CATABOLIC_PROCESS                                                                                           0.008997278
GOCC_CYTOSKELETON_OF_PRESYNAPTIC_ACTIVE_ZONE                                                                                                                     0.008997278
GOCC_SPERMATOPROTEASOME_COMPLEX                                                                                                                                  0.008997278
GOMF_OXIDOREDUCTASE_ACTIVITY_ACTING_ON_PAIRED_DONORS_WITH_OXIDATION_OF_A_PAIR_OF_DONORS_RESULTING_IN_THE_REDUCTION_OF_MOLECULAR_OXYGEN_TO_TWO_MOLECULES_OF_WATER 0.008997278
GOMF_SULFURTRANSFERASE_ACTIVITY                                                                                                                                  0.008997278
GOBP_REGULATION_OF_PEPTIDASE_ACTIVITY                                                                                                                            0.010639373
GOBP_MAINTENANCE_OF_CENTROSOME_LOCATION                                                                                                                          0.010787384
GOBP_PRESYNAPTIC_ACTIVE_ZONE_ORGANIZATION                                                                                                                        0.010787384
GOBP_PROTEIN_ACTIVATION_CASCADE                                                                                                                                  0.010787384
GOBP_REGULATION_OF_MRNA_EXPORT_FROM_NUCLEUS                                                                                                                      0.010787384
GOBP_RESCUE_OF_STALLED_RIBOSOME                                                                                                                                  0.010787384
GOBP_VESICLE_TETHERING                                                                                                                                           0.010787384
GOCC_NONHOMOLOGOUS_END_JOINING_COMPLEX                                                                                                                           0.010787384
                                                                                                                                                                 P.adj
GOBP_MOTOR_NEURON_MIGRATION                                                                                                                                      1
GOBP_NEURAL_CREST_CELL_MIGRATION_INVOLVED_IN_AUTONOMIC_NERVOUS_SYSTEM_DEVELOPMENT                                                                                1
GOBP_TRNA_THIO_MODIFICATION                                                                                                                                      1
GOCC_FIBRINOGEN_COMPLEX                                                                                                                                          1
GOBP_ORGANELLE_LOCALIZATION                                                                                                                                      1
GOBP_MAINTENANCE_OF_PRESYNAPTIC_ACTIVE_ZONE_STRUCTURE                                                                                                            1
GOMF_STRUCTURAL_CONSTITUENT_OF_PRESYNAPTIC_ACTIVE_ZONE                                                                                                           1
GOBP_RIBOSOME_ASSOCIATED_UBIQUITIN_DEPENDENT_PROTEIN_CATABOLIC_PROCESS                                                                                           1
GOCC_CYTOSKELETON_OF_PRESYNAPTIC_ACTIVE_ZONE                                                                                                                     1
GOCC_SPERMATOPROTEASOME_COMPLEX                                                                                                                                  1
GOMF_OXIDOREDUCTASE_ACTIVITY_ACTING_ON_PAIRED_DONORS_WITH_OXIDATION_OF_A_PAIR_OF_DONORS_RESULTING_IN_THE_REDUCTION_OF_MOLECULAR_OXYGEN_TO_TWO_MOLECULES_OF_WATER 1
GOMF_SULFURTRANSFERASE_ACTIVITY                                                                                                                                  1
GOBP_REGULATION_OF_PEPTIDASE_ACTIVITY                                                                                                                            1
GOBP_MAINTENANCE_OF_CENTROSOME_LOCATION                                                                                                                          1
GOBP_PRESYNAPTIC_ACTIVE_ZONE_ORGANIZATION                                                                                                                        1
GOBP_PROTEIN_ACTIVATION_CASCADE                                                                                                                                  1
GOBP_REGULATION_OF_MRNA_EXPORT_FROM_NUCLEUS                                                                                                                      1
GOBP_RESCUE_OF_STALLED_RIBOSOME                                                                                                                                  1
GOBP_VESICLE_TETHERING                                                                                                                                           1
GOCC_NONHOMOLOGOUS_END_JOINING_COMPLEX                                                                                                                           1

## Skipped exons

### Negative values corresponds to more skipped exons in CalTRAP samples

In [14]:
SE_cal_df <- signif_events_df[(signif_events_df$Event_type == "SE") & (signif_events_df$IncLevelDifference < 0),]
SE_cal_genes <- unique(SE_cal_df$geneSymbol)
print(length(SE_cal_genes))

[1] 559

In [15]:
enrich_SE_cal_df <- get_enrich(SE_cal_genes, all_genes, sets)
head(enrich_SE_cal_df, 20)

                                      Pval         P.adj
GOCC_NEURON_PROJECTION                4.452923e-27 4.630595e-23
GOCC_SYNAPSE                          3.482557e-25 1.810755e-21
GOCC_AXON                             4.027222e-23 1.395969e-19
GOBP_CELL_JUNCTION_ORGANIZATION       1.881614e-17 4.891727e-14
GOCC_POSTSYNAPSE                      2.688474e-15 5.591488e-12
GOMF_CYTOSKELETAL_PROTEIN_BINDING     7.733500e-15 1.340344e-11
GOBP_CYTOSKELETON_ORGANIZATION        9.130239e-14 1.356362e-10
GOCC_NEURON_TO_NEURON_SYNAPSE         1.402168e-13 1.822643e-10
GOBP_CELLULAR_COMPONENT_MORPHOGENESIS 9.701129e-13 1.065640e-09
GOBP_VESICLE_MEDIATED_TRANSPORT       1.024753e-12 1.065640e-09
GOCC_CELL_CORTEX                      2.882686e-12 2.725187e-09
GOBP_NEURON_DIFFERENTIATION           5.199935e-12 4.506177e-09
GOBP_SYNAPSE_ORGANIZATION             7.299814e-12 5.839290e-09
GOBP_CELL_PART_MORPHOGENESIS          8.240244e-12 6.120735e-09
GOCC_SOMATODENDRITIC_COMPARTMENT      3.251815e-11 2.254375e-08
GOBP_NEUROGENESIS                     4.633644e-11 3.011579e-08
GOCC_PRESYNAPSE                       5.446332e-11 3.331553e-08
GOCC_GLUTAMATERGIC_SYNAPSE            6.888759e-11 3.979789e-08
GOBP_NEURON_DEVELOPMENT               1.096598e-10 6.001853e-08
GOBP_CELL_MORPHOGENESIS               1.498471e-10 7.791298e-08

### Positive values corresponds to more skipped exons in control samples

In [16]:
SE_ctrl_df <- signif_events_df[(signif_events_df$Event_type == "SE") & (signif_events_df$IncLevelDifference > 0),]
SE_ctrl_genes <- unique(SE_ctrl_df$geneSymbol)
print(length(SE_ctrl_genes))

[1] 394

In [17]:
enrich_SE_ctrl_df <- get_enrich(SE_ctrl_genes, all_genes, sets)
head(enrich_SE_ctrl_df, 20)

                                                                         Pval
GOBP_CELL_JUNCTION_ORGANIZATION                                          4.443390e-08
GOCC_SYNAPSE                                                             1.148391e-07
GOBP_NEURON_DIFFERENTIATION                                              5.835430e-07
GOBP_CELL_PART_MORPHOGENESIS                                             7.446896e-07
GOBP_NEURON_DEVELOPMENT                                                  1.054712e-06
GOCC_GOLGI_APPARATUS                                                     1.148747e-06
GOBP_SYNAPSE_ORGANIZATION                                                1.216020e-06
GOCC_NEURON_PROJECTION                                                   2.141592e-06
GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION               2.676145e-06
GOCC_POSTSYNAPSE                                                         2.710261e-06
GOBP_NEUROGENESIS                                                        2.872017e-06
GOBP_MEMBRANE_DEPOLARIZATION_DURING_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL 3.214997e-06
GOBP_CELLULAR_COMPONENT_MORPHOGENESIS                                    4.364908e-06
GOBP_MEMBRANE_DEPOLARIZATION_DURING_ACTION_POTENTIAL                     4.421599e-06
GOBP_CELL_PROJECTION_ORGANIZATION                                        7.123739e-06
GOBP_NEGATIVE_REGULATION_OF_SPROUTING_ANGIOGENESIS                       9.261146e-06
GOMF_CELL_ADHESION_MOLECULE_BINDING                                      1.679190e-05
GOBP_CELL_MORPHOGENESIS                                                  2.215139e-05
GOMF_CYTOSKELETAL_PROTEIN_BINDING                                        2.946286e-05
GOCC_AXON                                                                3.219113e-05
                                                                         P.adj
GOBP_CELL_JUNCTION_ORGANIZATION                                          0.0004620681
GOCC_SYNAPSE                                                             0.0005971059
GOBP_NEURON_DIFFERENTIATION                                              0.0018064853
GOBP_CELL_PART_MORPHOGENESIS                                             0.0018064853
GOBP_NEURON_DEVELOPMENT                                                  0.0018064853
GOCC_GOLGI_APPARATUS                                                     0.0018064853
GOBP_SYNAPSE_ORGANIZATION                                                0.0018064853
GOCC_NEURON_PROJECTION                                                   0.0027151007
GOBP_CELL_MORPHOGENESIS_INVOLVED_IN_NEURON_DIFFERENTIATION               0.0027151007
GOCC_POSTSYNAPSE                                                         0.0027151007
GOBP_NEUROGENESIS                                                        0.0027151007
GOBP_MEMBRANE_DEPOLARIZATION_DURING_CARDIAC_MUSCLE_CELL_ACTION_POTENTIAL 0.0027860632
GOBP_CELLULAR_COMPONENT_MORPHOGENESIS                                    0.0032843007
GOBP_MEMBRANE_DEPOLARIZATION_DURING_ACTION_POTENTIAL                     0.0032843007
GOBP_CELL_PROJECTION_ORGANIZATION                                        0.0049386508
GOBP_NEGATIVE_REGULATION_OF_SPROUTING_ANGIOGENESIS                       0.0060191660
GOMF_CELL_ADHESION_MOLECULE_BINDING                                      0.0102717063
GOBP_CELL_MORPHOGENESIS                                                  0.0127973518
GOMF_CYTOSKELETAL_PROTEIN_BINDING                                        0.0161254903
GOCC_AXON                                                                0.0164334699

## Mutally exclusive exons

In [18]:
MXE_df <- signif_events_df[signif_events_df$Event_type == "MXE",]
MXE_genes <- unique(MXE_df$geneSymbol)
print(length(MXE_genes))

[1] 146

In [19]:
enrich_MXE_df <- get_enrich(MXE_genes, all_genes, sets)
head(enrich_MXE_df)

                                                  Pval         P.adj
GOBP_REGULATION_OF_TRANSPORT                      3.781070e-06 0.03931935
GOMF_GTPASE_ACTIVATOR_ACTIVITY                    1.202734e-05 0.04980134
GOMF_ENZYME_ACTIVATOR_ACTIVITY                    1.436715e-05 0.04980134
GOCC_SYNAPSE                                      6.066969e-05 0.15772603
GOMF_HIGH_VOLTAGE_GATED_CALCIUM_CHANNEL_ACTIVITY  1.305769e-04 0.27157381
GOMF_NUCLEOSIDE_TRIPHOSPHATASE_REGULATOR_ACTIVITY 1.919290e-04 0.33264501

## Alternative 3' splice site

### Negative values corresponds to longer 3' end in CalTRAP samples

In [20]:
A3SS_cal_df <- signif_events_df[(signif_events_df$Event_type == "A3SS") & (signif_events_df$IncLevelDifference < 0),]
A3SS_cal_genes <- unique(A3SS_cal_df$geneSymbol)
print(length(A3SS_cal_genes))

[1] 101

In [21]:
enrich_A3SS_cal_df <- get_enrich(A3SS_cal_genes, all_genes, sets)
head(enrich_A3SS_cal_df)

                                                             Pval         P.adj
GOBP_REGULATION_OF_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION 0.0002519270 1
GOBP_RAS_PROTEIN_SIGNAL_TRANSDUCTION                         0.0004205375 1
GOBP_REGULATION_OF_DNA_REPLICATION                           0.0009303182 1
GOMF_TRANSCRIPTION_REGULATOR_ACTIVITY                        0.0009506683 1
GOBP_SMALL_GTPASE_MEDIATED_SIGNAL_TRANSDUCTION               0.0013271432 1
GOMF_SEQUENCE_SPECIFIC_DNA_BINDING                           0.0014333817 1

### Positive values corresponds to longer 3' end in control samples

In [22]:
A3SS_ctrl_df <- signif_events_df[(signif_events_df$Event_type == "A3SS") & (signif_events_df$IncLevelDifference > 0),]
A3SS_ctrl_genes <- unique(A3SS_ctrl_df$geneSymbol)
print(length(A3SS_ctrl_genes))

[1] 88

In [23]:
enrich_A3SS_ctrl_df <- get_enrich(A3SS_ctrl_genes, all_genes, sets)
head(enrich_A3SS_ctrl_df)

                                                                             Pval
GOMF_TFIIB_CLASS_TRANSCRIPTION_FACTOR_BINDING                                0.0002376811
GOBP_NEURON_DIFFERENTIATION                                                  0.0003403521
GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS                            0.0004847589
GOBP_POSTTRANSCRIPTIONAL_REGULATION_OF_GENE_EXPRESSION                       0.0006416371
GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS 0.0006567793
GOBP_NEURON_DEVELOPMENT                                                      0.0007376079
                                                                             P.adj
GOMF_TFIIB_CLASS_TRANSCRIPTION_FACTOR_BINDING                                1
GOBP_NEURON_DIFFERENTIATION                                                  1
GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS                            1
GOBP_POSTTRANSCRIPTIONAL_REGULATION_OF_GENE_EXPRESSION                       1
GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS 1
GOBP_NEURON_DEVELOPMENT                                                      1

## Alternative 5' splice site

### Negative values corresponds to longer 5' end in CalTRAP samples

In [24]:
A5SS_cal_df <- signif_events_df[(signif_events_df$Event_type == "A5SS") & (signif_events_df$IncLevelDifference < 0),]
A5SS_cal_genes <- unique(A5SS_cal_df$geneSymbol)
print(length(A5SS_cal_genes))

[1] 49

In [25]:
enrich_A5SS_cal_df <- get_enrich(A5SS_cal_genes, all_genes, sets)
head(enrich_A5SS_cal_df)

                                                        Pval         P.adj
GOBP_POSITIVE_REGULATION_OF_DENDRITIC_SPINE_DEVELOPMENT 0.0001922430 1
GOBP_REGULATION_OF_CIRCADIAN_SLEEP_WAKE_CYCLE           0.0002547908 1
GOBP_CIRCADIAN_SLEEP_WAKE_CYCLE                         0.0005422862 1
GOMF_NEUREXIN_FAMILY_PROTEIN_BINDING                    0.0005422862 1
GOBP_REGULATION_OF_DENDRITIC_SPINE_DEVELOPMENT          0.0006442351 1
GOMF_TRANSCRIPTION_FACTOR_BINDING                       0.0007181913 1

### Positive values corresponds to longer 5' end in control samples

In [26]:
A5SS_ctrl_df <- signif_events_df[(signif_events_df$Event_type == "A5SS") & (signif_events_df$IncLevelDifference > 0),]
A5SS_ctrl_genes <- unique(A5SS_ctrl_df$geneSymbol)
print(length(A5SS_ctrl_genes))

[1] 52

In [27]:
enrich_A5SS_ctrl_df <- get_enrich(A5SS_ctrl_genes, all_genes, sets)
head(enrich_A5SS_ctrl_df)

                                        Pval         P.adj
GOBP_OXIDATIVE_RNA_DEMETHYLATION        8.261833e-05 0.4295740
GOMF_OXIDATIVE_RNA_DEMETHYLASE_ACTIVITY 8.261833e-05 0.4295740
GOBP_PEPTIDYL_LYSINE_MODIFICATION       1.427824e-04 0.4949314
GOBP_NEURON_DEVELOPMENT                 3.550625e-04 0.9215353
GOBP_PEPTIDYL_LYSINE_HYDROXYLATION      4.897763e-04 0.9215353
GOBP_CELL_RECOGNITION                   5.317061e-04 0.9215353